spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://192.168.43.18:3306/drivingcar?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: drivingcar
    password: drivingcar
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8081
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.ujs.drivingcar.pojo
markerhub:
  jwt:
    secret: drivingcar-app
    expire: 2592000000
    verifytime: 300000
    header: Authorization
shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379